### PR TITLE
fix(controller): use by default plural name

### PR DESCRIPTION
**Pull request by RomainLanz**
Controller must have a plural name as the doc show.

### CODE REVIEW

**Comment by RomainLanz** [comment]
I still donno why I had conflicts... Whatever, they are fixed.

**Comment by thetutlage** [comment]
I should leave it to the end user to type the correct name instead of generator pluralizing it, which may produce confusion

**Comment by RomainLanz** [comment]
That's true! It's up to you 😄

**Comment by thetutlage** [comment]
Closing then

**Pull request closed without merging**
